[package]
name = "mytable"
version = "0.1.0"
authors = ["Suhail Arshad <suhail_a@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
